name: Daily File Update

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC
  workflow_dispatch:     # Permet le déclenchement manuel

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner ton dépôt
        uses: actions/checkout@v3

      - name: Télécharger le fichier distant
        run: |
          curl -L https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt -o fichier.txt

      - name: Modifier le fichier
        run: |
          sed -i 's/||//g' fichier.txt
          sed -i 's/\^//g' fichier.txt
  
      - name: Commit et push des changements
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fichier.txt
          git commit -m "Fichier mis à jour automatiquement"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
