name: Daily File Update

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC
  workflow_dispatch:     # Permet le déclenchement manuel

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner ton dépôt
        uses: actions/checkout@v3

      - name: Télécharger les fichiers distants
        run: |
          curl -L https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt -o AdGuardDNS.txt
          curl -L https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt -o AdGuardDNS2.txt
          curl -L https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt -o AdGuardDNS5.txt
          curl -L https://nsfw.oisd.nl/ -o OISD.txt

      - name: Modifier les fichiers
        run: |
          sed -i 's/||//g' AdGuardDNS.txt
          sed -i 's/\^//g' AdGuardDNS.txt
          sed -i 's/||//g' AdGuardDNS2.txt
          sed -i 's/\^//g' AdGuardDNS2.txt
          sed -i 's/127\.0\.0\.1//g' AdGuardDNS2.txt
          sed -i 's/||//g' AdGuardDNS5.txt
          sed -i 's/\^//g' AdGuardDNS5.txt
          sed -i 's/||//g' OISD.txt
          sed -i 's/\^//g' OISD.txt


      - name: Commit et push des changements
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add AdGuardDNS.txt
          git add AdGuardDNS2.txt
          git add AdGuardDNS5.txt
          git add OISD.txt
          git commit -m "Fichiers mis à jour automatiquement"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
